# Week 7 Lecture Part II
In this lecture we will apply the random sampling methods to Tables.

In [2]:
from datascience import *
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

from urllib.request import urlopen 
import re
def read_url(url): 
    return re.sub('\\s+', ' ', urlopen(url).read().decode())

In [3]:
# read the file NBA_SALARIES2015.csv into a table
nba = Table.read_table("NBA_SALARIES2015.csv")
nba

RANK | PLAYER            | POSITION | TEAM                  | SALARY ($M)
1    | Kobe Bryant       | SF       | Los Angeles Lakers    | 25
2    | Joe Johnson       | SF       | Brooklyn Nets         | 24.8949
3    | LeBron James      | SF       | Cleveland Cavaliers   | 22.9705
4    | Carmelo Anthony   | SF       | New York Knicks       | 22.875
5    | Dwight Howard     | C        | Houston Rockets       | 22.3594
6    | Chris Bosh        | PF       | Miami Heat            | 22.1927
7    | Chris Paul        | PG       | Los Angeles Clippers  | 21.4687
8    | Kevin Durant      | SF       | Oklahoma City Thunder | 20.1586
9    | Derrick Rose      | PG       | Chicago Bulls         | 20.0931
11   | LaMarcus Aldridge | PF       | San Antonio Spurs     | 19.689
... (406 rows omitted)

In [4]:
np.arange(0, 416)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415])

In [8]:
# there at 416 players take a simple random sample of 20 records.
cf = np.random.choice(np.arange(416), 20)
cf

array([153, 147, 142, 298, 350, 204, 221, 199, 341, 348, 282, 118, 132,
       250, 112,  29,  72, 300, 279,   4])

In [9]:
#Take a simple random sample of 20 players in the nba dataset.
nba.take(cf)

RANK | PLAYER           | POSITION | TEAM                   | SALARY ($M)
155  | Mike Dunleavy    | SG       | Chicago Bulls          | 4.5
149  | Trevor Booker    | PF       | Utah Jazz              | 4.775
144  | Darren Collison  | PG       | Sacramento Kings       | 5.01356
300  | Mason Plumlee    | C        | Portland Trail Blazers | 1.41552
352  | Montrezl Harrell | PF       | Houston Rockets        | 1
206  | Meyers Leonard   | PF       | Portland Trail Blazers | 3.07588
223  | Furkan Aldemir   | PF       | Philadelphia 76ers     | 2.83677
201  | Ben McLemore     | SG       | Sacramento Kings       | 3.1566
343  | Richaun Holmes   | PF       | Philadelphia 76ers     | 1.07417
350  | Joe Young        | PG       | Indiana Pacers         | 1.00703
... (10 rows omitted)

In [15]:
nba_1 = nba.with_columns('Record', np.arange(0, 416))
nba_1

RANK | PLAYER            | POSITION | TEAM                  | SALARY ($M) | Record
1    | Kobe Bryant       | SF       | Los Angeles Lakers    | 25          | 0
2    | Joe Johnson       | SF       | Brooklyn Nets         | 24.8949     | 1
3    | LeBron James      | SF       | Cleveland Cavaliers   | 22.9705     | 2
4    | Carmelo Anthony   | SF       | New York Knicks       | 22.875      | 3
5    | Dwight Howard     | C        | Houston Rockets       | 22.3594     | 4
6    | Chris Bosh        | PF       | Miami Heat            | 22.1927     | 5
7    | Chris Paul        | PG       | Los Angeles Clippers  | 21.4687     | 6
8    | Kevin Durant      | SF       | Oklahoma City Thunder | 20.1586     | 7
9    | Derrick Rose      | PG       | Chicago Bulls         | 20.0931     | 8
11   | LaMarcus Aldridge | PF       | San Antonio Spurs     | 19.689      | 9
... (406 rows omitted)

In [22]:
# get systematic random sample
n = nba.num_rows
# m is sample size
m = 20
# number of 20 sections in data set
k = int(n/m)
# random number record to start with
start = np.random.choice(k)
systematic = np.arange(start, n, k)
nn = len(systematic)

if nn > 20:
    systematic = np.delete(systematic, nn-1)

nba.take(systematic)

RANK | PLAYER          | POSITION | TEAM                   | SALARY ($M)
5    | Dwight Howard   | C        | Houston Rockets        | 22.3594
26   | Roy Hibbert     | C        | Los Angeles Lakers     | 15.5922
46   | Tyson Chandler  | C        | Phoenix Suns           | 13
66   | Monta Ellis     | SG       | Indiana Pacers         | 10.3
86   | Channing Frye   | PF       | Orlando Magic          | 8.19303
106  | Ed Davis        | C        | Portland Trail Blazers | 6.9808
126  | Martell Webster | SF       | Washington Wizards     | 5.6135
146  | Chris Andersen  | PF       | Memphis Grizzlies      | 5
166  | Aaron Gordon    | PF       | Orlando Magic          | 4.17168
186  | Terrence Ross   | SF       | Toronto Raptors        | 3.55392
... (10 rows omitted)